# Generated by Django 4.2.1 on 2023-05-19 18:38

from django.db import migrations
import oddamwdobreręce.managers


class Migration(migrations.Migration):

    dependencies = [
        ('oddamwdobreręce', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', oddamwdobreręce.managers.CustomUserManager()),
            ],
        ),
    ]
